Jotter/accounts/urls.py
from django.urls import path, include
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', SignUp.as_view(), name="signup"),
    path('profile/<str:username>/', Profile.as_view(), name="profile"),
    path('follow/<str:username>/', follow, name="follow"),
    path('unfollow/<str:username>/', unfollow, name="unfollow"),
    path('profileDetails/<str:username>/', ProfileDetails.as_view(), name="profileDetails"),
]

Jotter/blog/urls.py
from django.urls import path
from .views import *


app_name = 'blog'

urlpatterns = [
    path('', Index.as_view(), name="index"),
    path('topic/<str:uuid>/', TopicDetail.as_view(), name="topicDetail"),
    path('post/new-post/', NewPost.as_view(), name="newPost"),
    path('post/<str:slug>/', PostDetail.as_view(), name="postDetail"),
    path('comment/<str:uuid>/', newComment, name="newComment"),
    path('like/<str:uuid>/', like, name="like"),
    path('unlike/<str:uuid>/', unlike, name="unlike"),
    path('subscribe/<str:uuid>/', subscribe, name="subscribe"),
    path('unsubscribe/<str:uuid>/', unsubscribe, name="unsubscribe"),
    path('search/', search, name='search'),
    path('tag/<str:tag>/', Tag.as_view(), name="tag"),
    path('draft/', newDraft, name="newDraft"),
]

Jotter/jotter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

Jotter/blog/models.py
from django.db import models
from django.conf import settings
from uuid import uuid4
from django.template.defaultfilters import slugify

class Topic(models.Model):
    title = models.CharField(max_length=25)
    uuid = models.UUIDField(default=uuid4)

    def __str__(self):
        return self.title

class Post(models.Model):
    uuid = models.UUIDField(default=uuid4, auto_created=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=150, null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    dateAdded = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=False)
    tags = models.CharField(max_length=50, null=True, blank=True)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, through='LikeRelation', related_name='likedPosts')
    draft = models.BooleanField(default=False)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-dateAdded',)
    
    def save(self, *args, **kwargs): 
        if not self.slug:
            slugList = self.title.split(' ')
            self.slug = slugify(slugList[:5])
        return super().save(*args, **kwargs)
    
    def like(self, user):
        relation = LikeRelation.objects.get_or_create(author=user, post=self)
        return relation
    
    def unlike(self, user):
        relation = LikeRelation.objects.get(author=user, post=self)
        if relation:
            relation.delete()

class Draft(models.Model):
    uuid = models.UUIDField(default=uuid4, auto_created=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=150, null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    dateAdded = models.DateTimeField(auto_now_add=True)
    tags = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ('-dateAdded',)

    
class LikeRelation(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('author', 'post')

    def __str__(self):
        return f"'{self.author}' likes '{self.post}'"

class Comment(models.Model):
    uuid = models.UUIDField(default=uuid4)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')
    text = models.TextField()
    dateAdded = models.DateTimeField(auto_now_add=True, auto_created=True)
    
    def __str__(self):
        return ' '.join(self.text.split(' ')[:5])
    
    class Meta:
        ordering = ['-dateAdded']

Jotter/blog/forms.py
from django import forms
from .models import Post, Comment, Topic

class PostForm(forms.ModelForm):
    error_css_class = "error"
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Title', 'class': 'post-title'}))
    text = forms.CharField(widget=forms.Textarea(attrs={'class': 'post-text', 'placeholder': 'Text'}))
    tags = forms.CharField(widget=forms.TextInput(attrs={'class': 'tags', 'form': 'newPostForm'}))
    topic = forms.ModelChoiceField(empty_label='Select a topic', queryset=Topic.objects.all(), widget=forms.Select(attrs={'form': 'newPostForm'}))
    class Meta:
        model = Post 
        fields = ['title', 'text', 'topic', 'tags']
    field_order = ['title', 'text', 'topic', 'tags']

    def clean(self):
        super(PostForm, self).clean()
        title = self.cleaned_data['title']
        text = self.cleaned_data['text']
        tags = self.cleaned_data['tags']
        topic = self.cleaned_data['topic']

        if len(title) < 10:
            self.add_error('title', 'Please enter a more descriptive title')

        if len(text) < 200:
            self.add_error('text', 'Minimum text length is 200 characters')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

Jotter/blog/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from .models import Post, Topic, Comment
from accounts.models import CustomUser
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, JsonResponse
from itertools import chain
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class Index(ListView):
    model = Post 
    template_name = "blog/index.html"

    def get(self, request, *args, **kwargs):
        posts = super(Index, self).get_queryset()
        top = posts[0]
        try:
            three = posts[1:4]
            posts = posts[4:]
        except IndexError:
            three = None 
            posts = posts[1:]
        return render(request, self.template_name, {'posts': posts, 'top': top, 'three': three})

@method_decorator(login_required, name="dispatch")
class TopicDetail(DetailView):
    model = Topic 
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'
    template_name = "blog/topicDetail.html"

    def get(self, request, *args, **kwargs):
        topic = super(TopicDetail, self).get_object()
        posts = topic.post_set.all()
        subscribers = topic.subscribers.all()
        subscribed = False 
        if topic in request.user.topics.all():
            subscribed = True 
        context = {'posts': posts, 'topic': topic, 'subscribed': subscribed, 'subscribers': subscribers}
        return render(request, self.template_name, context)
    
class PostDetail(DetailView):
    model = Post 
    template_name = "blog/postDetail.html"
    slug_field = "slug"

    def get(self, request, *args, **kwargs):
        post = super(PostDetail, self).get_object()
        tags = post.tags.split(',')
        comments = post.comment_set.all()
        like = False 
        if post in request.user.likedPosts.all():
            like = True
        context = {'post': post, 'comments': comments, 'tags': tags, 'like': like}
        return render(request, self.template_name, context)
    
@method_decorator(login_required, name="dispatch")
class NewPost(CreateView):
    form_class = PostForm
    model = Post
    success_url = reverse_lazy("blog:index")
    template_name = "blog/newPost.html"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        self.object = None
        if form.is_valid():
            newPost = form.save(commit=False)
            newPost.author = request.user
            newPost.save()
            return HttpResponseRedirect(self.success_url)
        else:
            return self.form_invalid(form)

@method_decorator(login_required, name="dispatch") 
class NewComment(CreateView):
    form_class = CommentForm
    model = Comment 
    template_name = "blog/newComment.html"
    
    def form_valid(self, form):
        post_uuid = self.kwargs.get('uuid')
        post = get_object_or_404(Post, uuid=post_uuid)
        form.instance.post = post
        form.instance.author = self.request.user
        return super(NewComment, self).form_valid(form)
    
    def get_success_url(self):
        post_uuid = self.kwargs['uuid']
        post = get_object_or_404(Post, uuid=post_uuid)
        return reverse("blog:postDetail", args=[post.slug])

@login_required
def subscribe(request, uuid):
    topic = get_object_or_404(Topic, uuid=uuid)
    request.user.topics.add(topic)
    return JsonResponse({'message': 'success'})

@login_required
def unsubscribe(request, uuid):
    topic = get_object_or_404(Topic, uuid=uuid)
    request.user.topics.remove(topic)
    return JsonResponse({'message': 'success'})

def search(request):
    if request.method == 'GET':
        query = request.GET['search']
        topics = Topic.objects.filter(title__icontains=query)
        posts = Post.objects.filter(text__icontains=query) | Post.objects.filter(title__icontains=query)
        authors = CustomUser.objects.filter(first_name__icontains=query) | CustomUser.objects.filter(last_name__icontains=query) | CustomUser.objects.filter(username__icontains=query)
        comments = Comment.objects.filter(text__icontains=query)
        results = {'topics': topics, 'posts': posts, 'authors': authors, 'comments': comments}
        return render(request, 'blog/search.html', {'results': results, 'query': query })

@login_required   
def newComment(request, uuid):
    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            post = get_object_or_404(Post, uuid=uuid)
            text = form.cleaned_data['text']
            newComment = Comment(post=post, text=text)
            newComment.author = request.user
            newComment.save()
            return JsonResponse({'success': 'your response was posted'})
        
@login_required
def like(request, uuid):
    post = Post.objects.get(uuid=uuid)
    post.like(request.user)
    return JsonResponse({'success': 'post liked'})

@login_required
def unlike(request, uuid):
    post = Post.objects.get(uuid=uuid)
    post.unlike(request.user)
    return JsonResponse({'success': 'post liked'})

@method_decorator(login_required, name='dispatch')
class Tag(ListView):
    model = Post 
    template_name = "blog/tag.html"

    def get(self, request, *args, **kwargs):
        tag = self.kwargs['tag']
        posts = super(Tag, self).get_queryset().filter(tags__icontains=tag)
        return render(request, self.template_name, {'tag': tag, 'posts': posts})
    

@login_required()
def newDraft(request):
    if request.method == 'POST':
        return JsonResponse({"success": "new draft added"})

Jotter/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'blog/css/base.css' %}">
    {% block staticfiles %}
    {% endblock staticfiles %}
    <title>
        {% block title %}
        Jotter
        {% endblock title %}
    </title>
</head>

<body>
    <div class="navbar">
        <a href="{% url 'blog:index' %}">
            <div class="logo">
                <img src="{% static 'blog/icons/post.svg' %}" alt="" style="width: 50px;">
                Jotter
            </div>
        </a>
        <form action="{% url 'blog:search' %}" method="GET">
            <div class="search">
                <span>
                    <img src="{% static 'blog/icons/magnify.svg' %}" alt="" height="25px">
                </span>
                <input type="search" placeholder="Search posts, authors, topics" autocomplete="off" name='search'>
            </div>
        </form>
        <div class="authlinks">
            {% if user.is_authenticated %}
            <a href="{% url 'accounts:profile' user.username %}" class="profile">
                <button>Profile</button>
            </a>
            <a href="{% url 'accounts:logout' %}" class="logout">
                <button>Logout</button>
            </a>
            {% else %}
            <a href="{% url 'accounts:login' %}" class="login">
            <button>Login</button>
            </a>
            <a href="{% url 'accounts:signup' %}" class="logout">
            <button>Signup</button>
            </a>
            {% endif %}
        </div>
    </div>
    <div class="main">
        {% block content %}
        {% endblock content %}
    </div>
</body>

</html>

Jotter/blog/templates/blog/blogComment.html
<div class="comment-main">
    <div class="comment-div">
        <div class="text">{{ comment.text }}</div>
        <div class="footer">
            <div class="author-date"><a href="{% url 'accounts:profile' comment.author %}">{{ comment.author }}</a> • {{ comment.dateAdded|date:"F jS"|lower }}</div>
        </div>
    </div>
</div>

Jotter/blog/templates/blog/blogPost.html
{% load static %}

<div class="post">
    <div class="header">
        <div class="topic"><a href="{% url 'blog:topicDetail' post.topic.uuid %}">{{ post.topic|upper }}</a></div>
        <div class="time">{{ post.dateAdded|date:"F jS o" }}</div>
    </div>
    <div class="title"><a href="{% url 'blog:postDetail' post.slug %}">{{ post.title|upper }}</a></div>
    <div class="content">{{ post.text|truncatewords:70 }}</div>
</div>

Jotter/blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load static %}

{% block staticfiles %}
<link rel="stylesheet" href="{% static 'blog/css/index.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/blogPost.css' %}">
{% endblock staticfiles %}

{% block content %}
{% if user.is_authenticated %}
<a href="{% url 'blog:newPost' %}">
    <button class="newPost">
        <img src="{% static 'blog/icons/pen.svg' %}" width="15px" alt="">
    </button>
</a>
{% endif %}
<div class="main">
    <div class="header">
        <div class="top">
            <img src="{% static 'blog/img/blank.jpg' %}" alt="">
            <div class="time">{{ top.dateAdded|date:"F jS o" }}</div>
            <div class="title"><a href="{% url 'blog:postDetail' top.slug %}">{{ top.title|upper }}</a></div>
            <div class="content">{{ top.text|truncatewords:50 }}</div>
        </div>
        <div class="side">
            {% for post in three %}
            <div class="three">
                <div class="image">
                    <img src="{% static 'blog/img/blank.jpg' %}" alt="">
                </div>
                <div class="title">
                    <div class="time">{{ post.dateAdded|date:"F jS o" }}</div>
                    <div class="title"><a href="{% url 'blog:postDetail' post.slug %}">{{ post.title|upper }}</a></div>
                </div>
            </div>
            {% empty %}
            {% endfor %}
        </div>
    </div>
    {% for post in posts %}
    {% include "blog/blogPost.html" %}
    {% empty %}
    <p> . </p>
    {% endfor %}
</div>
{% endblock content %}

Jotter/blog/templates/blog/newComment.html
{% extends "blog/base.html" %}

{% block title %}
    Comment 
{% endblock title %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
{% endblock content %}

Jotter/blog/templates/blog/newPost.html
{% extends "blog/base.html" %}
{% load static %}

{% block staticfiles %}
<link rel="stylesheet" href="{% static 'blog/css/newPost.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/newPostField.css' %}">
<script src="{% static 'blog/js/newPost.js' %}" defer></script>
<!-- <script src="{% static 'blog/js/drafts.js' %}" defer></script> -->
{% endblock staticfiles %}

{% block title %}
Jot
{% endblock title %}

{% block content %}
<script>
    var draftUrl = "{% url 'blog:newDraft' %}";
</script>

<div class="newPost">
    <!-- <div class="drafts">
        <div class="draft-title">Drafts</div>
        <div class="draft-cards">
            <a href="">
                <div class="draft">
                    <div class="title">Lorem ipsum dolor sit amet</div>
                    <div class="body">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos doloribus neque veritatis molestiae perferendis tempora fuga repellendus nihil numquam iusto quo soluta corporis voluptatibus distinctio ullam in, vel velit perspiciatis?</div>
                    <div class="tags">vel, velit, perspiciatis</div>
                </div>
            </a>
            <a href="">
                <div class="draft">
                    <div class="title">Lorem ipsum dolor sit amet</div>
                    <div class="body">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos doloribus neque veritatis molestiae perferendis tempora fuga repellendus nihil numquam iusto quo soluta corporis voluptatibus distinctio ullam in, vel velit perspiciatis?</div>
                    <div class="tags">vel, velit, perspiciatis</div>
                </div>
            </a>
        </div>
    </div> -->
    <div class="postmain">
        <div class="title"></div>
        <div class="newPost-form">
            <form action="{% url 'blog:newPost' %}" method="POST" id="newPostForm">
                {% csrf_token %}
                {% for field in form %}
                {% if field.name != 'topic' and field.name != 'tags' %}
                {% include 'blog/newPostField.html' %}
                {% else %}
                {% endif %}
                {% endfor %}
            </form>
        </div>
    </div>
    <div class="aside">
        <div class="post-author">
            <div class="title">Author</div>
            <div class="name">
                <div class="profileImage"></div>
                {{ user.get_full_name }} 
            </div>
        </div>
        <div class="topic-tags">
            {% for field in form %}
            {% if field.name == 'topic' or field.name == 'tags' %}
            <div class="aside-field">
                <div class="title">{{ field.name|title }}</div>
                <div class="errors">{{ field.errors }}</div>
                <div class="field">{{ field }}</div>
            </div>
            {% else %}
            {% endif %}
            {% endfor %}
            <div class="post-date">
                <div class="header">Post Date</div>
                <div class="date">
                    <div class="content"></div>
                    <div class="icon"></div>
                </div>
                <div class="time">
                    <div class="content"></div>
                    <div class="icon"></div>
                </div>
            </div>
        </div>
        <div class="buttons">
            <input type="submit" form="newPostForm" class="submit">
            <!-- <a href="{% url 'blog:newDraft' %}"><button class="draft">Draft</button></a> -->
        </div>
    </div>
</div>
{% endblock content %}

Jotter/blog/templates/blog/newPostField.html
<div class="post-field">
    <div class="errors">{{ field.errors }}</div>
    <div class="field">{{ field }}</div>
</div>

Jotter/blog/templates/blog/postDetail.html
{% extends "blog/base.html" %}
{% load static %}

{% block staticfiles %}
<link rel="stylesheet" href="{% static 'blog/css/postDetail.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/blogComment.css' %}">
<script src="{% static 'blog/js/postDetail.js' %}" defer></script>
{% endblock staticfiles%}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<script>
    const likeUrl = "{% url 'blog:like' post.uuid %}";
    const unlikeUrl = "{% url 'blog:unlike' post.uuid %}";
</script>

<div class="postDetail">
    <div class="header">
        <div class="auth-time"><a href="{% url 'accounts:profile' post.author %}">@{{ post.author }}</a> • {{ post.dateAdded|date:"F jS o" }}</div>
        <div class="auth"></div>
        <div class="title">{{ post.title|title }}</div>
        <div class="topic"><a href="{% url 'blog:topicDetail' post.topic.uuid %}">{{ post.topic|upper }}</a></div>
        <div class="tags">
            {% for tag in tags %}
            <a href="{% url 'blog:tag' tag %}">
                <div class="tag">{{ tag }}</div>
            </a>
            {% empty %}
            {% endfor %}
        </div>
    </div>
    <div class="content">
        {{ post.text|linebreaks }}
        <div class="feedback">
            <div>
                {% if like %}
                <img src="{% static 'blog/icons/thumb-up.svg' %}" alt="">
                <a href="#" class="dislike">dislike</a>
                <a href="#" class="like" style="display: none;">like</a>
                {% else %}
                <img src="{% static 'blog/icons/thumb-up.svg' %}" alt="" style="display: none;">
                <a href="#" class="like">like</a>
                <a href="#" class="dislike" style="display: none;">dislike</a>
                {% endif %}
            </div>
            {% if user.is_authenticated %}
            <div class="reply"><img src="{% static 'blog/icons/reply.svg' %}" alt=""> Reply</div>
            {% endif %}
        </div>
    </div>
    <div class="commentState success" style="display: none">
    </div>
    <div class="newComment" style="display: none">
        <div class="commentURL" hidden>{% url 'blog:newComment' post.uuid %}</div>
        <form id="commentForm">
            {% csrf_token %}
            <input type="text" name="text" placeholder="Your response..." autocomplete="off">
        </form>
        <input type="submit" class="submit">
    </div>
    {% if comments %}
    <div class="comment">Comments</div>
    <div class="comments">
        {% for comment in comments %}
        {% include "blog/blogComment.html" %}
        {% empty %}
        {% endfor %}
    </div>
    {% else %}
    {% endif %}
</div>
{% endblock content %}

Jotter/blog/templates/blog/search.html
{% extends 'blog/base.html' %}
{% load static %}

{% block staticfiles %}
<link rel="stylesheet" href="{% static 'accounts/css/topicTab.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/blogPost.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/blogComment.css' %}">
<link rel="stylesheet" href="{% static 'accounts/css/profileTab.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/search.css' %}">
{% endblock staticfiles %}

{% block title %}
{{ query }}
{% endblock title %}

{% block content %}
<div class="search-main">
    {% if not results.topic and not results.posts and not results.comments and not results.authors %}
    <div class="noResults">
        <div class="blank"></div>
        <div class="message">No results for <span>"{{ query }}"</span></div>
    </div>
    {% else %}
        {% if results.topics %}
        <div class="search-topic search-title"></div>
        {% for topic in results.topics %}
        {% include 'registration/topicTab.html' %}
        {% endfor %}
        {% else %}
        {% endif %}
        {% if results.posts %}
        <div class="search-post search-title">Posts</div>
        {% for post in results.posts %}
        {% include 'blog/blogPost.html' %}
        {% endfor %}
        {% else %}
        {% endif %}
        {% if results.comments %}
        <div class="search-comment search-title">Comments</div>
        {% for comment in results.comments %}
        {% include 'blog/blogComment.html' %}
        {% endfor %}
        {% else %}
        {% endif %}
        {% if results.authors %}
        <div class="search-author search-title">Authors</div>
        {% for author in results.authors %}
        {% include 'registration/profileTab.html' with profile=author %}
        {% endfor %}
        {% else %}
        {% endif %}
    {% endif %}
</div>
{% endblock content %}

Jotter/blog/templates/blog/tag.html
{% extends 'blog/base.html' %}
{% load static %}

{% block staticfiles %}
<link rel="stylesheet" href="{% static 'blog/css/blogPost.css' %}">
<link rel="stylesheet" href="{% static 'blog/css/tag.css' %}">
{% endblock staticfiles %}

{% block title %}
    {{ tag|title }}
{% endblock title %}

{% block content %}
<div class="title">#{{ tag }}</div>
<div class="tag-subtitle">{{ posts|length }} post(s)</div>
<div class="tag-posts">
    {% for post in posts %}
    {% include 'blog/blogPost.html' %}
    {% endfor %}
</div>
{% endblock content %}

Jotter/blog/templates/blog/topicDetail.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %}
{{ topic }}
{% endblock title %}

{% block staticfiles %}
    <link rel="stylesheet" href="{% static 'blog/css/blogPost.css' %}">
    <script src="{% static 'blog/js/topicDetail.js' %}" defer></script>
    <link rel="stylesheet" href="{% static 'blog/css/topicDetails.css' %}">
{% endblock staticfiles %}

{% block content %}
<script>
    var subUrl = "{% url 'blog:subscribe' topic.uuid %}";
    var unsubUrl = "{% url 'blog:unsubscribe' topic.uuid %}"
</script>

<div class="topic-main">
    <div class="topic-header">
        <div class="bg-overlay"></div>
        <div class="title">{{ topic.title|title }}</div>
        <div class="followers">{{ subscribers|length }}</div>
        {% if subscribed %}
            <button class="unsub">Unsubscribe</button>
        {% else %}
            <button class="sub">Subscribe</button>
        {% endif %}
    </div>
    <div class="topic-content">
        {% for post in posts %}
        {% include "blog/blogPost.html" %}
        {% empty %}
        {% endfor %}
    </div>
</div>
{% endblock content %}