Jotter/blog/urls.py
from django.urls import path
from .views import *


app_name = 'blog'

urlpatterns = [
    path('', Index.as_view(), name="index"),
    path('topic/<str:uuid>/', TopicDetail.as_view(), name="topicDetail"),
    path('post/new-post/', NewPost.as_view(), name="newPost"),
    path('post/<str:slug>/', PostDetail.as_view(), name="postDetail"),
    path('comment/<str:uuid>/', newComment, name="newComment"),
    path('like/<str:uuid>/', like, name="like"),
    path('unlike/<str:uuid>/', unlike, name="unlike"),
    path('subscribe/<str:uuid>/', subscribe, name="subscribe"),
    path('unsubscribe/<str:uuid>/', unsubscribe, name="unsubscribe"),
    path('search/', search, name='search'),
    path('tag/<str:tag>/', Tag.as_view(), name="tag"),
    path('draft/', newDraft, name="newDraft"),
]

Jotter/core/urls.py
from django.urls import path 
from . import views 

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('like/<str:uuid>/', views.likePost, name='likePost'),
    path('post/<str:uuid>/<slug:slug>/', views.postDetails, name='postDetails'),
    path('delete/<str:uuid>/', views.deletePost, name='deletePost'),
    path('create-a-new-post/', views.createPost.as_view(), name='createPost'),
]

Jotter/jotter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blog.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
]

Jotter/core/views.py
from django.shortcuts import render, redirect
from .models import Post, Topic
from django.views.generic import View
from .forms import postForm

def index(request):
    posts = Post.objects.all().order_by('-dateAdded')
    topics = Topic.objects.all()
    context = {'posts': posts, 'topics': topics}
    return render(request, 'core/index.html', context)

def likePost(request, uuid):
    post = Post.objects.get(uuid=uuid)
    if post.likes:
        post.likes += 1
    else:
        post.likes = 1
    post.save()
    return redirect('core:index')

def postDetails(request, uuid, slug):
    post = Post.objects.get(uuid=uuid)
    tags = post.tags.split(',')
    context = {'post': post, 'tags': tags}
    return render(request, 'core/postDetails.html', context)

def deletePost(request, uuid):
    post = Post.objects.get(uuid=uuid)
    post.delete()
    return redirect('core:index')

class createPost(View):
    template_name = 'core/createPost.html'
    form = postForm

    def get(self, request):
        form = self.form()
        return render(request, self.template_name, {'form': form})
    
    def post(self, request):
        form = self.form(data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:index')
        else: 
            return 

Jotter/core/templates/core/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Jotter</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {% block css %}
    {% endblock css %}
</head>

<body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="#">Jotter</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:index' %}">Feed</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Contact</a>
            </li>
        </ul>
    </nav>

    {% block body %}
    {% endblock body %}

    <footer class="bg-light fixed-bottom">
        <div class="container">
            <p class="text-center text-muted">&copy; 2023 Jotter. All Rights Reserved.</p>
        </div>
    </footer>
</body>

</html>

Jotter/core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'core/css/index.css' %}">
{% endblock css %}

{% block body %}
<div class="container mt-3">
    <div class="row indexHeader">
        <h1>Posts</h1>
        <a href="{% url 'core:createPost' %}" class="btn btn-success btn-sm">New Post</a>
    </div>
    <hr>

    <div class="col">
        {% for post in posts %}
        <div class="card mt-3">
            <div class="card-body">
                <h5 class="card-title">Writer's Name</h5>
                <h6 class="card-subtitle mb-2 text-muted">@writerhandle</h6>
                <p class="card-text">{{ post.title }}</p>
            </div>
            <div class="card-footer">
                <div class="row">
                    {% if post.likes %}
                    <div class="col-6">
                        {% if post.likes == 1 %}
                        <small class="text-muted">{{ post.likes }} like</small>
                        {% else %}
                        <small class="text-muted">{{ post.likes }} likes</small>
                        {% endif %}
                    </div>
                    {% else %}
                    <div class="col-6">
                        <small class="text-muted">No likes</small>
                    </div>
                    {% endif %}
                </div>
                <div class="row">
                    <div class="col-6">
                        <a href="{% url 'core:likePost' post.uuid %}" class="card-link"><i class="far fa-thumbs-up"></i>
                            Like</a>
                    </div>
                    <div class="col-6 text-right">
                        <a href="{% url 'core:postDetails' post.uuid post.slug %}" class="card-link">Read More <i class="fas fa-arrow-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="col-sm-6 col-lg-12 mx-auto">
            <div class="card">
                <div class="card-body">
                    <p class="card-text">No Posts</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock body %}

Jotter/core/templates/core/postDetails.html
{% extends 'core/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'core/css/postDetails.css' %}">
{% endblock css %}

{% block body %}
<div class="container mt-3">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="mb-4">{{ post.title }}</h1>
            <div class="row ml-2">
                <p class="font-weight-light">Tags:</p>
                {% for tag in tags %}
                <a href="#" class="font-italic">{{ tag }}, </a>
                {% empty %}
                {% endfor %}
            </div>
            <p class="text-muted mb-4">By Writer's Name on {{ post.dateAdded | date:'F d, Y'}}</p>
            <p>{{ post.text }}</p>
            <hr>
            <div class="row dateAndLikes">
                <p class="text-muted">Likes: {{ post.likes }} | Date: {{ post.dateAdded | date:'F d, Y'}}</p>
                <a href="{% url 'core:deletePost' post.uuid %}" class="btn btn-danger btn-sm">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock body %}